"""Bilingual data tables for the interactive memory modules.

Every explanatory string is "中文｜English"; interactive_content.bi() splits on
the fullwidth bar and renders both. **bold** is rendered as <strong>.
"""

# (code, name_en, name_zh, region, capital, premier, lt_gov, facts[])
PROVINCES = [
    ("BC", "British Columbia", "卑詩省（不列顛哥倫比亞）", "West Coast",
     "Victoria 維多利亞", "David Eby（NDP）", "Wendy Cocchia（Lt. Governor）",
     ["木材、礦業、鮭魚捕撈、電影業（Hollywood North）｜Forestry, mining, salmon fishing, film industry (Hollywood North)",
      "華人移民歷史悠久，溫哥華是亞太門戶｜Long history of Chinese immigration; Vancouver is the gateway to the Asia-Pacific",
      "Vancouver 是大城，**Victoria** 才是首府（位於溫哥華島）｜Vancouver is the big city, but **Victoria** (on Vancouver Island) is the capital"]),
    ("AB", "Alberta", "亞伯達省", "Prairie Provinces",
     "Edmonton 艾德蒙頓", "Danielle Smith（UCP）", "Salma Lakhani（Lt. Governor）",
     ["石油、天然氣（油砂 Oil Sands）、農業、牛肉｜Oil, natural gas (oil sands), agriculture, beef",
      "Rocky Mountains 洛磯山脈、Banff／Jasper 國家公園｜Rocky Mountains; Banff and Jasper National Parks",
      "**Calgary** 是最大城但 **Edmonton** 才是首府｜**Calgary** is the largest city, but **Edmonton** is the capital"]),
    ("SK", "Saskatchewan", "薩克其萬省", "Prairie Provinces",
     "Regina 里賈納", "Scott Moe（Sask Party）", "Russ Mirasty（Lt. Governor）",
     ["小麥（Wheat Province）、鉀礦、鈾礦｜Wheat (the \"wheat province\"), potash, uranium",
      "加拿大穀倉，40% 的可耕地｜Canada's breadbasket, 40% of the arable land",
      "Saskatoon 是大城但 **Regina** 才是首府，RCMP 訓練學院在此｜Saskatoon is the big city, but **Regina** is the capital and home of the RCMP academy"]),
    ("MB", "Manitoba", "曼尼托巴省", "Prairie Provinces",
     "Winnipeg 溫尼伯", "Wab Kinew（NDP，首位原住民省長）", "Anita Neville（Lt. Governor）",
     ["農業、礦業、水力發電｜Agriculture, mining, hydro-electric power",
      "Louis Riel 起義的核心地（Métis 文化）；1916 第一個給婦女投票權的省｜Heart of Louis Riel's uprising (Métis culture); first province to give women the vote (1916)",
      "1870 年加入聯邦（第 5 省）｜Joined Confederation in 1870 (the fifth province)"]),
    ("ON", "Ontario ⭐", "安大略省", "Central Canada",
     "Toronto 多倫多", "Doug Ford（Progressive Conservative）",
     "Edith Dumont（Lt. Governor，首位法裔安省人，2023 起）",
     ["製造業、金融、服務業、科技｜Manufacturing, finance, services, technology",
      "**國都 Ottawa 渥太華位於此省**（不是 Toronto！）｜**The national capital, Ottawa, is in Ontario** (not Toronto!)",
      "人口最多的省（超過三分之一的加拿大人）｜The most populous province (more than one-third of Canadians)",
      "主要城市：Toronto、Ottawa、Hamilton、Mississauga、London｜Major cities: Toronto, Ottawa, Hamilton, Mississauga, London",
      "**考試 Ontario 省題重點**：省長 Doug Ford（2018 起），省督 Edith Dumont（2023 起）｜**Ontario exam facts**: Premier Doug Ford (since 2018), Lieutenant Governor Edith Dumont (since 2023)",
      "記住你的選區：聯邦議員 MP 與省議員 MPP｜Know your riding: your MP (federal) and MPP (provincial)",
      "與美國邊境最長，五大湖區（Great Lakes）｜Longest border with the U.S.; the Great Lakes"]),
    ("QC", "Quebec", "魁北克省", "Central Canada",
     "Quebec City 魁北克市", "François Legault（CAQ）", "Manon Jeannotte（Lt. Governor）",
     ["航太、水電、礦業、紙漿與紙、軟體｜Aerospace, hydro-electricity, mining, pulp and paper, software",
      "**唯一以法語為唯一官方語言的省**｜**The only province whose sole official language is French**",
      "Montreal 蒙特婁是大城但 **Quebec City** 才是首府｜Montreal is the big city, but **Quebec City** is the capital",
      "天主教文化深厚、保留法國民法｜Deep Catholic heritage; keeps French civil law",
      "1980、1995 兩次主權公投都未通過｜Sovereignty referendums in 1980 and 1995 both failed"]),
    ("NB", "New Brunswick", "新布藍瑞克省", "Atlantic Canada",
     "Fredericton 弗雷德里克頓", "Susan Holt（Liberal，2024 起）", "Louise Imbeault（Lt. Governor）",
     ["林業、漁業、食品加工｜Forestry, fishing, food processing",
      "**加拿大唯一官方雙語（英＋法）的省份**｜**Canada's only officially bilingual (English and French) province**",
      "Acadian 文化重鎮；Saint John 最大城，Moncton 法語中心｜Acadian heartland; Saint John is the largest city, Moncton the Francophone centre"]),
    ("NS", "Nova Scotia", "新斯科細亞省", "Atlantic Canada",
     "Halifax 哈利法克斯", "Tim Houston (Progressive Conservative)", "Mike Savage (Lt. Governor)",
     ["漁業、造船、旅遊｜Fishing, shipbuilding, tourism",
      "**Bluenose 帆船**——10 分硬幣圖案｜The **Bluenose** schooner appears on the 10-cent coin",
      "**Pier 21** 全國移民登陸博物館｜**Pier 21**, the national museum of immigration",
      "**Bay of Fundy** 全球最高潮汐｜The **Bay of Fundy** has the world's highest tides",
      "1758 第一個民選議會；Halifax 有加拿大最大海軍基地｜First elected assembly (1758); Halifax has Canada's largest naval base"]),
    ("PE", "Prince Edward Island", "愛德華王子島（PEI）", "Atlantic Canada",
     "Charlottetown 夏洛特敦", "Rob Lantz (PC, 2025 起)", "Wassim Salamoun (Lt. Governor)",
     ["馬鈴薯（產量全國第一）、觀光業、漁業｜Potatoes (Canada's top producer), tourism, fishing",
      "**面積最小的省**｜**The smallest province**",
      "**Confederation 發源地**——1864 Charlottetown Conference｜**Birthplace of Confederation** — the 1864 Charlottetown Conference",
      "《清秀佳人 Anne of Green Gables》故鄉；Confederation Bridge 連接本土｜Home of Anne of Green Gables; linked to the mainland by the Confederation Bridge"]),
    ("NL", "Newfoundland and Labrador", "紐芬蘭與拉布拉多省", "Atlantic Canada",
     "St. John's 聖約翰斯", "Andrew Furey (Liberal)", "Joan Marie Aylward (Lt. Governor)",
     ["漁業（鱈魚 Cod）、海上石油、水電｜Fishing (cod), offshore oil, hydro-electricity",
      "**最晚加入聯邦的省（1949）**｜**The last province to join Confederation (1949)**",
      "**最東邊的省份**，有自己的時區｜**The most easterly province**, with its own time zone",
      "維京人 L'Anse aux Meadows 北美最早歐洲遺址｜L'Anse aux Meadows, the Viking site, is the earliest European settlement in North America"]),
    ("YT", "Yukon", "育空地區", "Northern Territories",
     "Whitehorse 白馬市", "Ranj Pillai (Liberal)", "Adeline Webber (Commissioner)",
     ["礦業、觀光｜Mining, tourism",
      "**1890 年代 Klondike 淘金潮**｜**The Klondike Gold Rush of the 1890s**",
      "Mount Logan 加拿大最高峰；全國最低溫紀錄 −63°C｜Mount Logan, Canada's highest mountain; coldest temperature ever recorded in Canada, −63°C"]),
    ("NT", "Northwest Territories", "西北地區", "Northern Territories",
     "Yellowknife 黃刀鎮", "R.J. Simpson (Independent)", "Gerald W. Kisoun (Commissioner)",
     ["鑽石、石油、天然氣；Yellowknife「北美鑽石之都」｜Diamonds, oil, gas; Yellowknife is the \"diamond capital of North America\"",
      "Mackenzie River 北美第二長河｜The Mackenzie River, North America's second-longest river system",
      "超過一半人口是原住民（Dene、Inuit、Métis）｜More than half the population is Aboriginal (Dene, Inuit, Métis)"]),
    ("NU", "Nunavut", "努納福特地區", "Northern Territories",
     "Iqaluit 伊魁特", "P.J. Akeeagok", "Eva Aariak (Commissioner)",
     ["礦業（金、鐵、鑽石）、傳統手工藝｜Mining (gold, iron, diamonds), traditional arts",
      "**1999 從 NT 分出來新建**（最年輕的領地）｜**Created in 1999 from the eastern Northwest Territories** (the youngest territory)",
      "**Inuit 因紐特人為多數**（85%）；Inuktitut 意為「我們的土地」｜**About 85% Inuit**; Nunavut means \"our land\" in Inuktitut",
      "19 席議會以共識制選出省長｜The 19-member assembly chooses a premier by consensus"]),
]

# (year_label, title_zh, title_en, era, brief, details[])
HISTORY_EVENTS = [
    ("1497", "John Cabot 抵達加拿大東岸", "John Cabot reaches Atlantic shores", "new-france",
     "為英王宣稱大西洋岸土地，第一個繪製加拿大東岸地圖的人｜Claimed the Atlantic coast for the English king and was the first to map Canada's East Coast",
     ["義大利航海家受英王委派｜An Italian navigator sailing for the English king",
      "登陸地點可能是 Newfoundland｜Probably landed in Newfoundland",
      "為日後英國對加宣稱主權奠基｜Laid the basis for later British claims"]),
    ("1534", "Cartier 命名 'Canada'", "Cartier names 'Canada'", "new-france",
     "Jacques Cartier 三次航行（1534–42），從原住民聽到 'kanata'（村莊）一詞｜Jacques Cartier made three voyages (1534–42) and heard the Iroquoian word kanata, \"village\"",
     ["為法王 François I 宣稱聖羅倫斯地區｜Claimed the St. Lawrence region for King Francis I of France",
      "'Canada' 名字源自 Iroquois 語 'kanata'（村莊）｜The name Canada comes from kanata, \"village\"",
      "1550 年代起 Canada 出現在地圖上｜By the 1550s the name appeared on maps"]),
    ("1604", "首座歐洲永久定居 Port-Royal", "Port-Royal — first permanent settlement", "new-france",
     "Pierre de Monts 與 Samuel de Champlain 在 Acadia 建立佛羅里達以北第一個歐洲聚落｜Pierre de Monts and Samuel de Champlain founded the first European settlement north of Florida, in Acadia",
     ["位於今日 Nova Scotia｜In present-day Nova Scotia",
      "Acadia 文化由此開始｜The beginning of Acadian culture"]),
    ("1608", "Champlain 建立 Québec City", "Champlain founds Quebec City", "new-france",
     "Samuel de Champlain 在聖羅倫斯河岸建立 Québec City，'Father of New France'｜Champlain built a fortress at Québec City and is called the Father of New France",
     ["這是 New France 的首都｜Capital of New France",
      "Champlain 與 Algonquin、Montagnais、Huron 結盟；法國與 Iroquois 1701 締和｜Allied with the Algonquin, Montagnais and Huron; peace with the Iroquois in 1701",
      "毛皮貿易（海狸皮）是經濟核心｜The fur trade (beaver pelts) drove the economy"]),
    ("1670", "Hudson's Bay Company 成立", "Hudson's Bay Company chartered", "new-france",
     "英王 Charles II 給予 HBC 對 Hudson Bay 流域的貿易壟斷權｜King Charles II granted the HBC exclusive trading rights over the Hudson Bay watershed",
     ["與 Montreal 商人競爭一百年｜Competed with Montreal-based traders for 100 years",
      "voyageurs 與 coureurs des bois 乘獨木舟貿易｜Voyageurs and coureurs des bois travelled by canoe"]),
    ("1755", "Acadian 大流亡", "Acadian Deportation", "new-france",
     "1755–63 英國驅逐三分之二以上的 Acadian｜Between 1755 and 1763 the British deported more than two-thirds of the Acadians",
     ["稱為「大動盪」Great Upheaval｜Known as the \"Great Upheaval\"",
      "Acadian 文化存活至今，是法語加拿大的一部分｜Acadian culture survived and thrives today"]),
    ("1759", "Plains of Abraham 之戰 ⚔️", "Battle of the Plains of Abraham", "british",
     "**英軍 James Wolfe vs. 法軍 Montcalm**，英軍奪下 Québec City，法國在美洲的帝國結束｜**Wolfe (British) vs. Montcalm (French)** — the British took Québec City and France's empire in America ended",
     ["**考試重點戰役**｜**Key exam battle**",
      "兩位將軍都陣亡｜Both commanders were killed",
      "殖民地改名 Province of Quebec｜The colony was renamed the Province of Quebec"]),
    ("1763", "Treaty of Paris：法割讓北美", "Treaty of Paris", "british",
     "七年戰爭結束，新法蘭西正式割讓給英國｜End of the Seven Years' War; New France was ceded to Britain",
     ["Royal Proclamation 1763 首次保障原住民領土權利｜The Royal Proclamation of 1763 first guaranteed Aboriginal territorial rights"]),
    ("1774", "Quebec Act 保障法裔權利", "Quebec Act", "british",
     "英國保障法裔的天主教信仰、擔任公職權利與法國民法｜Britain allowed Catholics religious freedom and public office, and restored French civil law",
     ["加拿大憲政基礎之一｜One of the constitutional foundations of Canada",
      "保留英國刑法｜British criminal law was kept"]),
    ("1776-83", "美國革命，Loyalists 北逃", "American Revolution — Loyalists flee north", "british",
     "約 4 萬 'United Empire Loyalists' 從美國逃到 Nova Scotia 與 Quebec｜Some 40,000 United Empire Loyalists fled to Nova Scotia and Quebec",
     ["Joseph Brant 率莫霍克族效忠派入加｜Joseph Brant led Loyalist Mohawk into Canada",
      "約 3,000 黑人效忠派北上｜About 3,000 black Loyalists came north",
      "1791 Constitutional Act 將 Quebec 分為 Upper／Lower Canada｜The Constitutional Act of 1791 split Quebec into Upper and Lower Canada"]),
    ("1793", "上加拿大率先廢奴", "Upper Canada moves to abolish slavery", "british",
     "副總督 Simcoe 讓上加拿大成為大英帝國第一個邁向廢奴的省｜Lieutenant Governor Simcoe made Upper Canada the first province in the Empire to move toward abolition",
     ["1833 全帝國廢奴｜Slavery abolished throughout the Empire in 1833",
      "Underground Railroad 帶數千奴隸逃到加拿大｜Thousands of slaves reached Canada via the Underground Railroad"]),
    ("1812-14", "1812 戰爭 — 加拿大守住了 ⚔️", "War of 1812 — Canada survives", "british",
     "美國入侵，**加拿大志願軍、英軍、原住民聯軍擊退美軍**｜The U.S. invaded; **Canadian volunteers, British troops and First Nations repelled the invasion**",
     ["**考試重點**｜**Key exam topic**",
      "Sir Isaac Brock 攻下 Detroit，在 Queenston Heights 陣亡｜Brock captured Detroit and was killed at Queenston Heights",
      "原住民領袖 Tecumseh 與英軍結盟｜Chief Tecumseh allied with the British",
      "Laura Secord 徒步 30 公里通報美軍動向｜Laura Secord walked 30 km to warn of an American attack",
      "1814 英軍燒了 Washington 白宮｜In 1814 the British burned the White House in Washington"]),
    ("1837-38", "Upper / Lower Canada 叛亂", "Rebellions of 1837-38", "british",
     "改革派起義被鎮壓，但促成 Lord Durham 報告與責任政府｜Reformers' rebellions were defeated but led to Lord Durham's report and responsible government",
     ["Durham 建議合併兩個加拿大並給予責任政府｜Durham recommended uniting the Canadas and granting responsible government",
      "促成 1840 Act of Union｜Led to the 1840 Act of Union"]),
    ("1840", "Act of Union 統一兩 Canada", "Act of Union", "british",
     "Upper + Lower Canada 合併為 'Province of Canada'｜Upper and Lower Canada were united as the Province of Canada",
     ["1847–48 Nova Scotia 第一個達成責任政府｜Nova Scotia attained responsible government first (1847–48)",
      "La Fontaine 1849 成為加拿大第一位責任政府領袖｜La Fontaine became the first leader of a responsible government in 1849"]),
    ("1864", "Charlottetown Conference", "Charlottetown Conference", "confederation",
     "Confederation 規劃會議在 PEI Charlottetown 舉行｜The conference that planned Confederation met in Charlottetown, PEI",
     ["**'Birthplace of Confederation'**｜**\"Birthplace of Confederation\"**",
      "與會者後稱 'Fathers of Confederation'｜The delegates became known as the Fathers of Confederation"]),
    ("1867 ⭐", "邦聯誕生 — Dominion of Canada", "Confederation — Dominion of Canada", "confederation",
     "**英國國會通過 British North America Act**，7 月 1 日加拿大自治領誕生｜**The British Parliament passed the British North America Act**; the Dominion of Canada was born July 1",
     ["**考試最重要日期之一**｜**One of the most important dates on the test**",
      "成立四省：Ontario、Quebec、Nova Scotia、New Brunswick｜Four provinces: Ontario, Quebec, Nova Scotia, New Brunswick",
      "**首任總理 Sir John A. Macdonald**｜**First Prime Minister: Sir John A. Macdonald**",
      "George-Étienne Cartier 是魁北克的聯邦之父｜George-Étienne Cartier was the key architect from Quebec",
      "7 月 1 日 = **Canada Day**（1982 前叫 Dominion Day）｜July 1 = **Canada Day** (Dominion Day until 1982)"]),
    ("1869-70", "Manitoba 加入 + Riel 起義", "Manitoba joins + Riel Rebellion", "confederation",
     "Métis 領袖 Louis Riel 在 Red River 起義，Manitoba 1870 加入聯邦｜Métis leader Louis Riel led the Red River uprising; Manitoba joined in 1870",
     ["Louis Riel 被許多人視為 Manitoba 之父｜Riel is seen by many as the father of Manitoba",
      "1885 第二次起義（North-West Rebellion）後被處決｜Executed after the 1885 North-West Rebellion",
      "1873 成立 North West Mounted Police｜The North West Mounted Police was created in 1873"]),
    ("1871", "British Columbia 加入", "British Columbia joins", "confederation",
     "BC 同意加入聯邦，條件是建一條橫貫鐵路｜B.C. joined on the promise of a railway to the West Coast", []),
    ("1873", "Prince Edward Island 加入", "PEI joins", "confederation",
     "PEI 1873 加入｜PEI joined in 1873", []),
    ("1885", "太平洋鐵路完成 🚂", "Canadian Pacific Railway completed", "confederation",
     "11 月 7 日打下最後一根道釘，鐵路橫貫東西｜The last spike was driven on November 7; the railway linked Canada from sea to sea",
     ["Donald Smith（Lord Strathcona）打下 Last Spike｜Donald Smith (Lord Strathcona) drove the last spike",
      "華工大量參與築路，之後遭人頭稅歧視；2006 政府道歉｜Built with Chinese labour; the Head Tax followed; the government apologized in 2006",
      "為加拿大統一的象徵｜A powerful symbol of unity"]),
    ("1898", "Yukon Territory 與 Klondike 淘金潮", "Yukon Territory & Klondike Gold Rush", "confederation",
     "Klondike 淘金潮帶來人口爆炸，Yukon 正式成為 territory｜The Klondike Gold Rush brought thousands; Yukon became a territory", []),
    ("1905", "Alberta、Saskatchewan 加入", "Alberta & Saskatchewan join", "confederation",
     "兩省同時從 North-West Territories 切出｜Both were carved from the North-West Territories", []),
    ("1914-18", "WWI — Vimy Ridge 🌹", "WWI — Vimy Ridge", "wars",
     "**1917 年 4 月加拿大軍團攻下 Vimy Ridge**——加拿大民族認同的關鍵時刻｜**In April 1917 the Canadian Corps captured Vimy Ridge** — a defining moment for Canadian identity",
     ["**考試重點**：4 月 9 日 = Vimy Day｜**Exam point**: April 9 is Vimy Day",
      "60 萬人服役、6 萬人陣亡｜600,000 served, 60,000 killed",
      "1918 年 11 月 11 日停戰｜Armistice on November 11, 1918"]),
    ("1916-18", "婦女選舉權", "Women's suffrage", "wars",
     "Manitoba 1916 首先給女性投票權，聯邦 1918 跟進｜Manitoba gave women the vote in 1916; most women got the federal vote in 1918",
     ["Dr. Emily Stowe 創立婦女參政運動｜Dr. Emily Stowe founded the suffrage movement",
      "1921 Agnes Macphail 第一位女性國會議員｜Agnes Macphail became the first woman MP in 1921"]),
    ("1929", "Persons Case — 女性是 'persons'", "Persons Case — women as legal persons", "wars",
     "Famous Five 打贏官司，女性法律上是 'persons'，可任參議員｜The Famous Five won the Persons Case; women were legally \"persons\" and could sit in the Senate",
     ["**Famous Five**：Emily Murphy 等 5 位女性｜**Famous Five**: Emily Murphy and four other women"]),
    ("1931", "Statute of Westminster", "Statute of Westminster", "wars",
     "英國國會確認加拿大等 Dominion 在外交與立法上完全自主｜Britain confirmed the Dominions' full autonomy in foreign affairs and legislation",
     ["加拿大實質獨立的法律基礎｜Legal basis of Canadian independence"]),
    ("1939-45", "WWII — D-Day Juno Beach", "WWII — D-Day at Juno Beach", "wars",
     "加軍在 D-Day（1944/6/6）登陸 Juno Beach；110 萬人服役、4.4 萬陣亡｜Canadians stormed Juno Beach on D-Day, June 6, 1944; 1.1 million served, 44,000 killed",
     ["**考試重點**｜**Key exam topic**",
      "Battle of the Atlantic：加拿大海軍護航｜The Royal Canadian Navy fought the Battle of the Atlantic",
      "戰後加拿大擁有世界第三大海軍｜Canada ended the war with the world's third-largest navy",
      "1988 為日裔加拿大人戰時遷移道歉｜Apology in 1988 for the wartime relocation of Japanese Canadians"]),
    ("1947", "Canadian Citizenship Act 通過", "Canadian Citizenship Act", "wars",
     "**加拿大公民身份首次法定**——之前是英國臣民｜**Canadian citizenship became a legal status** — before that Canadians were British subjects",
     ["**考試重點**：首次有 'Canadian citizen' 這個身份｜**Exam point**: first time there was a \"Canadian citizen\""]),
    ("1949", "Newfoundland 加入（最後一省）", "Newfoundland joins (last province)", "wars",
     "Newfoundland 1949 加入聯邦，完成 10 省版圖｜Newfoundland joined in 1949, completing the ten provinces",
     ["**考試重點**｜**Key exam topic**"]),
    ("1960", "原住民獲聯邦投票權", "Aboriginal people granted the vote", "modern",
     "原住民終於可以在聯邦選舉投票；1948 日裔加拿大人已獲投票權｜Aboriginal people were granted the vote in 1960; Japanese-Canadians in 1948", []),
    ("1965 ⭐", "楓葉旗誕生", "Maple Leaf flag adopted", "modern",
     "**新國旗首次升起**——紅白楓葉旗取代 Red Ensign｜**The new flag was raised for the first time** — the maple leaf replaced the Red Ensign",
     ["**考試重點**｜**Key exam topic**",
      "Lester B. Pearson 總理推動｜Promoted by Prime Minister Lester B. Pearson",
      "紅白自 1921 年起是國家代表色｜Red and white have been the national colours since 1921"]),
    ("1967", "Centennial / Order of Canada", "Centennial / Order of Canada", "modern",
     "聯邦 100 週年；加拿大勳章制度創立｜Centennial of Confederation; the Order of Canada was created",
     ["Montreal 世博會 Expo 67｜Expo 67 in Montreal"]),
    ("1969", "Official Languages Act", "Official Languages Act", "modern",
     "聯邦政府在全國提供英法雙語服務｜Guarantees French and English services in the federal government across Canada",
     ["**考試重點**｜**Key exam topic**",
      "Pierre Trudeau 推動；1970 加拿大協助創立 La Francophonie｜Under Pierre Trudeau; Canada helped found La Francophonie in 1970"]),
    ("1971", "多元文化主義政策", "Multiculturalism policy", "modern",
     "**加拿大成為世界第一個正式採取多元文化主義為國策的國家**｜**Canada became the first country to adopt multiculturalism as official policy**",
     ["1988 Canadian Multiculturalism Act 入法｜Canadian Multiculturalism Act, 1988"]),
    ("1980", "第一次 Quebec 公投", "First Quebec referendum", "modern",
     "魁北克主權公投未通過｜Quebec sovereignty was defeated in a referendum", []),
    ("1982 ⭐", "Constitution Act / Charter", "Constitution Act + Charter", "modern",
     "**憲法本土化**，加入《加拿大權利與自由憲章》｜**The Constitution was patriated** with the Canadian Charter of Rights and Freedoms",
     ["**考試最重要日期**｜**One of the most important dates on the test**",
      "Pierre Trudeau 推動；未獲 Quebec 同意｜Under Pierre Trudeau; without Quebec's agreement",
      "**Charter：基本自由、遷徙權、原住民權利、官方語言權、多元文化**｜**Charter: fundamental freedoms, mobility rights, Aboriginal rights, language rights, multiculturalism**"]),
    ("1995", "第二次 Quebec 公投", "Second Quebec referendum", "modern",
     "主權再次以些微差距未通過｜Sovereignty was narrowly defeated again", []),
    ("1999", "Nunavut 從 NT 分出", "Nunavut created", "modern",
     "**第三個 territory**，從 Northwest Territories 東部切出｜**The third territory**, created from the eastern Northwest Territories",
     ["**考試重點**：Nunavut 1999 年成立｜**Exam point**: Nunavut was established in 1999",
      "Inuit 為多數人口，首府 Iqaluit｜Mostly Inuit; capital Iqaluit"]),
    ("2008", "PM Harper 為寄宿學校道歉", "Harper apologizes for residential schools", "modern",
     "渥太華正式向寄宿學校前學生道歉｜Ottawa formally apologized to former residential school students", []),
    ("2021 ⭐", "TRC Day 國定假日", "Truth and Reconciliation Day", "modern",
     "**National Day for Truth and Reconciliation（9/30）正式列為國定假日**｜**September 30 became the National Day for Truth and Reconciliation**",
     ["**考試重點**：9 月 30 日｜**Exam point**: September 30",
      "穿橘色衣（Orange Shirt Day）紀念寄宿學校受害者｜Orange Shirt Day honours residential school survivors"]),
]

# (name_en, name_zh, party, years, facts[])
PRIME_MINISTERS = [
    ("Sir John A. Macdonald", "麥克唐納爵士", "Conservative", "1867-1873, 1878-1891",
     ["**首任總理（聯邦之父）**｜**First Prime Minister (Father of Confederation)**",
      "推動 Confederation 與太平洋鐵路｜Drove Confederation and the Canadian Pacific Railway",
      "生於蘇格蘭，1 月 11 日 Macdonald Day；$10 鈔票｜Born in Scotland; January 11 is Macdonald Day; $10 bill"]),
    ("Wilfrid Laurier", "勞里埃", "Liberal", "1896-1911",
     ["**第一位法裔總理**｜**First French-Canadian Prime Minister**",
      "鼓勵移民西部；Alberta、Saskatchewan 1905 加入｜Encouraged immigration to the West; Alberta and Saskatchewan joined in 1905",
      "$5 鈔票人物；11 月 20 日 Laurier Day｜On the $5 bill; November 20 is Laurier Day"]),
    ("Sir Robert Borden", "博登爵士", "Conservative", "1911-1920",
     ["帶領加拿大度過 WWI｜Led Canada through the First World War",
      "**1917 給婦女聯邦投票權（先護士、軍人親屬）**｜**Gave women the federal vote in 1917 (nurses and relatives of servicemen first)**",
      "$100 鈔票人物｜On the $100 bill"]),
    ("William Lyon Mackenzie King", "麥肯齊・金", "Liberal", "1921-1930, 1935-1948",
     ["**任期最長的總理**（22 年）｜**Longest-serving Prime Minister** (22 years)",
      "**1947 Canadian Citizenship Act**｜**Canadian Citizenship Act, 1947**",
      "$50 鈔票人物｜On the $50 bill"]),
    ("Louis St-Laurent", "聖羅倫", "Liberal", "1948-1957",
     ["推動 Newfoundland 1949 加入｜Newfoundland joined in 1949",
      "加拿大加入 NATO 北約｜Canada joined NATO",
      "建立 Trans-Canada Highway｜Trans-Canada Highway"]),
    ("John Diefenbaker", "迪芬貝克", "Progressive Conservative", "1957-1963",
     ["**1960 通過 Canadian Bill of Rights**｜**Canadian Bill of Rights, 1960**",
      "**1960 給原住民聯邦投票權**｜**Aboriginal people granted the federal vote, 1960**",
      "Saskatchewan 出身｜From Saskatchewan"]),
    ("Lester B. Pearson", "皮爾遜", "Liberal", "1963-1968",
     ["**諾貝爾和平獎得主**（1957，推動 UN 維和）｜**Nobel Peace Prize** (1957, UN peacekeeping)",
      "**1965 推動楓葉旗誕生**｜**The maple leaf flag, 1965**",
      "**1966 全民健保 Medicare** 立法｜**Medicare, 1966**",
      "Toronto Pearson 機場以他命名｜Toronto Pearson Airport is named after him"]),
    ("Pierre Trudeau", "老杜魯道", "Liberal", "1968-1979, 1980-1984",
     ["**1969 Official Languages Act**｜**Official Languages Act, 1969**",
      "**1971 多元文化主義**｜**Multiculturalism policy, 1971**",
      "**1982 Constitution Act + Charter ⭐**｜**Constitution Act and Charter, 1982 ⭐**"]),
    ("Brian Mulroney", "穆隆尼", "Progressive Conservative", "1984-1993",
     ["1988 **Multiculturalism Act 入法**｜**Multiculturalism Act, 1988**",
      "**1988 與美國自由貿易**（後 NAFTA、CUSMA）｜**Free trade with the U.S., 1988** (later NAFTA, CUSMA)",
      "1988 為日裔加拿大人道歉｜Apologized to Japanese Canadians in 1988"]),
    ("Jean Chrétien", "克雷蒂安", "Liberal", "1993-2003",
     ["**1995 第二次 Quebec 公投**期間任內｜In office during the **1995 Quebec referendum**",
      "1999 創建 Nunavut｜Nunavut created in 1999",
      "拒絕加入 2003 伊拉克戰爭｜Kept Canada out of the 2003 Iraq War"]),
    ("Paul Martin", "馬丁", "Liberal", "2003-2006",
     ["前財政部長，平衡預算｜Former finance minister who balanced the budget",
      "短暫任期｜Short term in office"]),
    ("Stephen Harper", "哈珀", "Conservative", "2006-2015",
     ["**2006 為華人人頭稅道歉；2008 為寄宿學校道歉 ⭐**｜**Apologized for the Head Tax (2006) and residential schools (2008) ⭐**",
      "Alberta 出身｜From Alberta"]),
    ("Justin Trudeau", "小杜魯道", "Liberal", "2015-2025",
     ["**老杜魯道之子**｜**Son of Pierre Trudeau**",
      "**2021 TRC Day 國定假日 ⭐**｜**Truth and Reconciliation Day, 2021 ⭐**",
      "推動大麻合法化（2018）｜Legalized cannabis (2018)"]),
    ("Mark Carney", "卡尼", "Liberal", "2025-至今",
     ["**前 Bank of Canada 與 Bank of England 行長**｜**Former Governor of the Bank of Canada and the Bank of England**",
      "**2025 就任現任總理**｜**Prime Minister since 2025**"]),
]

# (name_en, name_zh, colour, leader, status, facts[])
PARTIES = [
    ("Liberal Party", "自由黨", "#d71920", "Mark Carney", "現執政黨（2025-）｜Governing party (since 2025)",
     ["中間偏左｜Centre-left", "支持多元文化、社會福利｜Multiculturalism, social programs", "現任 PM 政黨｜The Prime Minister's party"]),
    ("Conservative Party", "保守黨", "#1A4782", "Pierre Poilievre", "官方反對黨｜Official Opposition",
     ["中間偏右｜Centre-right", "支持經濟自由、傳統價值｜Economic freedom, traditional values", "2003 由 PC 黨與聯盟黨合併｜Formed in 2003 by merging the PC and Alliance parties"]),
    ("New Democratic Party (NDP)", "新民主黨", "#F58220", "Don Davies (interim, 2025)",
     "第三大黨｜Third party", ["左派、勞工｜Left, labour", "推動社會醫療與社福｜Public health care and social programs"]),
    ("Bloc Québécois", "魁北克集團", "#0088CE", "Yves-François Blanchet", "只在魁北克省競選｜Runs only in Quebec",
     ["主張魁北克利益與主權｜Quebec interests and sovereignty", "只在 Quebec 推候選人｜Candidates only in Quebec"]),
    ("Green Party", "綠黨", "#3D9B35", "Jonathan Pedneault & Elizabeth May",
     "環保政黨｜Environmental party", ["氣候變遷、永續政策｜Climate and sustainability", "規模較小，在西岸有支持｜Small party with West Coast support"]),
]

VOTE_STEPS = [
    ("🇨🇦", "1. 公民身份｜1. Citizenship", "必須是 Canadian Citizen（永久居民不能投）｜You must be a Canadian citizen (permanent residents cannot vote)"),
    ("🎂", "2. 年滿 18 歲｜2. Age 18", "投票日當天滿 18｜At least 18 years old on voting day"),
    ("📬", "3. 選民資訊卡｜3. Voter information card", "Elections Canada 寄出，列出投票時間地點｜Mailed by Elections Canada; lists when and where to vote"),
    ("🏠", "4. 到投票站｜4. Go to the polling station", "帶卡片＋身分與地址證明｜Bring the card and proof of identity and address"),
    ("✏️", "5. 圈選候選人｜5. Mark your ballot", "在候選人旁的圓圈畫 X，摺好交給工作人員｜Mark an X beside your candidate, fold it and hand it to the poll official"),
]

MUST_KNOW_FACTS = [
    ("選舉週期｜Election cycle", "每 4 年 10 月第三個星期一（PM 可請 GG 提前）｜Third Monday in October every four years (the PM may ask the Governor General for an earlier election)"),
    ("選區與議員｜Ridings and MPs", "每個選區選一位 MP；得票最多者當選｜Each riding elects one MP; the candidate with the most votes wins"),
    ("誰當總理｜Who becomes PM", "眾議院席次最多政黨的領袖，由總督邀請組閣｜The leader of the party with the most seats, invited by the Governor General"),
    ("多數／少數政府｜Majority / minority", "席次過半＝多數政府；不到一半＝少數政府｜At least half the seats = majority; fewer = minority government"),
    ("Ontario 你的選區｜Your Ontario riding", "記住你的 MP（聯邦）和 MPP（省議員）姓名｜Know the names of your MP (federal) and MPP (provincial)"),
]

# (zh, en, desc)
JUSTICE_PRINCIPLES = [
    ("法治", "Rule of Law", "沒人凌駕於法律之上，包括政府、法官、警察｜No one is above the law, including governments, judges and the police"),
    ("無罪推定", "Presumption of Innocence", "被證明有罪前人人無辜｜Everyone is innocent until proven guilty"),
    ("正當程序", "Due Process", "政府必須尊重每個人依法享有的所有權利｜The government must respect all the legal rights a person is entitled to"),
    ("人身保護令", "Habeas Corpus", "挑戰國家非法拘留的權利，來自英國普通法｜The right to challenge unlawful detention, from English common law"),
    ("法律之下的自由", "Freedom under the Law", "法律提供秩序與和平解決糾紛的方式｜Laws provide order and a peaceful way to settle disputes"),
]

RCMP_FACTS = [
    ("聯邦警察｜Federal police", "在全加拿大執行聯邦法律｜Enforces federal laws throughout Canada"),
    ("省警察｜Provincial police", "在 Ontario、Quebec 以外的省與地區擔任省警｜Serves as provincial police everywhere except Ontario and Quebec"),
    ("市鎮警察｜Municipal police", "也在一些市鎮服務；各省都有市警察局｜Also serves some municipalities; every province has municipal police departments"),
    ("象徵｜Symbol", "紅色制服、Stetson 帽、Musical Ride——加拿大最知名象徵之一｜Red Serge, Stetson hat, Musical Ride — one of Canada's best-known symbols"),
    ("歷史｜History", "1873 由 Macdonald 成立 North West Mounted Police，總部 Regina｜Founded in 1873 as the North West Mounted Police; headquartered in Regina"),
    ("你的權利｜Your rights", "可以質疑警察的服務或行為，幾乎所有警力都有申訴程序｜You may question the police about their service or conduct; almost all forces have a complaint process"),
]

# (emoji, zh, en, brief, facts[])
SYMBOLS = [
    ("🍁", "楓葉", "Maple Leaf", "加拿大最著名的象徵｜Canada's best-known symbol",
     ["1700 年代法裔加拿大人採用｜Adopted by French Canadians in the 1700s",
      "1850 年代起出現在軍服上｜On Canadian uniforms since the 1850s",
      "刻在陣亡將士墓碑上｜Carved on the headstones of fallen soldiers"]),
    ("🚩", "國旗", "National Flag", "紅白楓葉旗｜The red-and-white maple leaf flag",
     ["**1965 年**首次升起｜**First raised in 1965**",
      "紅白色來自皇家軍事學院旗；1921 起為國家代表色｜Red and white come from the Royal Military College flag; national colours since 1921",
      "前身 Red Ensign 用了約 100 年｜The Red Ensign served for about 100 years"]),
    ("👑", "王權 / 君主", "The Crown", "King Charles III｜King Charles III",
     ["**2022 年 9 月 Elizabeth II 過世，Charles III 即位**｜**Elizabeth II died in September 2022; Charles III became King**",
      "王權象徵政府：國會、法院、警察、軍隊｜The Crown symbolizes government: Parliament, courts, police, the Forces",
      "Governor General Mary Simon 代表君主｜Represented by Governor General Mary Simon"]),
    ("🦫", "海狸", "Beaver", "5 分硬幣上的勤勞動物｜The industrious animal on the five-cent coin",
     ["哈德遜灣公司的象徵｜Symbol of the Hudson's Bay Company",
      "1834 成為 St. Jean Baptiste Society 標誌｜Emblem of the St. Jean Baptiste Society from 1834",
      "也在 Saskatchewan、Alberta 省徽上｜Also on the arms of Saskatchewan and Alberta"]),
    ("🛡️", "國徽與格言", "Coat of Arms", "一戰後採用｜Adopted after the First World War",
     ["含英、法、蘇、愛象徵與紅楓葉｜Symbols of England, France, Scotland and Ireland, with red maple leaves",
      "格言 'A mari usque ad mare'＝從海到海｜Motto A mari usque ad mare = \"from sea to sea\"",
      "出現在鈔票、政府文件、公共建築｜Seen on dollar bills, government documents and public buildings"]),
    ("🎵", "國歌", "O Canada", "1980 正式國歌｜Proclaimed the national anthem in 1980",
     ["1880 首次在 Québec City 演唱｜First sung in Québec City in 1880",
      "**2018 改 'in all of us command'**｜**Lyric changed to \"in all of us command\" in 2018**",
      "皇家國歌是 'God Save the King'｜The Royal Anthem is \"God Save the King\""]),
    ("🌹", "Vimy Ridge", "Vimy Ridge", "1917 加拿大關鍵戰役｜Canada's defining battle of 1917",
     ["4 月 9 日 = Vimy Day｜April 9 is Vimy Day",
      "「大英帝國突擊部隊」美名｜Won the reputation of \"shock troops of the British Empire\"",
      "法國 Vimy 有加拿大紀念碑｜The Vimy Memorial stands in France"]),
    ("🎖️", "Order of Canada", "加拿大勳章", "1967 設立｜Established in 1967, the centennial",
     ["加拿大自己的榮譽制度｜Canada's own honours system",
      "最高榮譽是維多利亞十字勳章（96 位加拿大人）｜The highest honour is the Victoria Cross (96 Canadians)"]),
    ("💰", "Loonie & Toonie", "1 元、2 元硬幣", "Loonie 1987、Toonie 1996｜Loonie 1987, Toonie 1996",
     ["Loonie：1 元，刻 Loon 潛鳥｜Loonie: $1 with a loon",
      "Toonie：2 元，刻 Polar Bear 北極熊｜Toonie: $2 with a polar bear"]),
    ("📜", "Magna Carta", "大憲章 1215", "有序自由 800 年的起源｜Origin of 800 years of ordered liberty",
     ["1215 年英國簽署｜Signed in England in 1215",
      "**Habeas Corpus** 來自英國普通法｜**Habeas corpus** comes from English common law",
      "憲章序言承認上帝至高與法治｜The Charter's preamble recognizes the supremacy of God and the rule of law"]),
]

# (denomination, name_en, name_zh, note)
CURRENCY_FIGURES = [
    ("$5", "Wilfrid Laurier", "勞里埃", "第一位法裔總理｜First French-Canadian Prime Minister"),
    ("$10", "Viola Desmond ⭐", "Viola Desmond", "**2018 起首位非白人女性**——民權先驅（2021 版指南仍寫 Macdonald）｜**First non-white woman on a bill (2018)**, a civil rights pioneer (the 2021 guide still says Macdonald)"),
    ("$20", "Queen Elizabeth II", "伊莉莎白二世", "新版將換 King Charles III｜New notes will show King Charles III"),
    ("$50", "Mackenzie King", "麥肯齊・金", "任期最長的總理｜Longest-serving Prime Minister"),
    ("$100", "Robert Borden", "博登爵士", "一戰期間總理｜Prime Minister during the First World War"),
]

NATIONAL_HOLIDAYS = [
    ("1/1", "New Year's Day", "元旦"),
    ("1/11", "Sir John A. Macdonald Day", "麥克唐納爵士日"),
    ("復活節前週五、後週一", "Good Friday & Easter Monday", "耶穌受難日與復活節星期一"),
    ("4/9", "Vimy Day", "維米日"),
    ("5/25 前的週一", "Victoria Day", "維多利亞日（君主誕辰）"),
    ("6/24", "Fête nationale（Quebec）", "魁北克國慶日"),
    ("7/1 ⭐", "Canada Day", "加拿大日（聯邦 1867）"),
    ("9 月第一個週一", "Labour Day", "勞動節"),
    ("9/30 ⭐", "National Day for Truth and Reconciliation", "真相與和解日（2021 起）"),
    ("10 月第二個週一", "Thanksgiving Day", "感恩節"),
    ("11/11 ⭐", "Remembrance Day", "國殤紀念日（戴紅罌粟，11 時默哀）"),
    ("11/20", "Sir Wilfrid Laurier Day", "勞里埃爵士日"),
    ("12/25", "Christmas Day", "聖誕節"),
    ("12/26", "Boxing Day", "節禮日"),
]

COINS = [
    ("1¢", "Maple Leaf 楓葉", "已停產 2013｜Discontinued in 2013"),
    ("5¢", "Beaver 海狸 🦫", "國家動物｜The national animal"),
    ("10¢", "Bluenose 帆船 ⛵", "Nova Scotia 的名船｜Nova Scotia's famous schooner"),
    ("25¢", "Caribou 馴鹿 🦌", "北方的象徵｜A symbol of the North"),
    ("$1 Loonie", "Loon 潛鳥", "1987 起｜Since 1987"),
    ("$2 Toonie", "Polar Bear 北極熊 🐻‍❄️", "1996 起｜Since 1996"),
]

# (zh, en, percent, colour, desc)
INDUSTRIES = [
    ("服務業", "Service industries", 75, "#c8102e",
     "運輸、教育、醫療、建築、銀行、通訊、零售、旅遊、政府——超過 75% 的工作｜Transportation, education, health care, construction, banking, communications, retail, tourism, government — more than 75% of jobs"),
    ("製造業", "Manufacturing industries", 13, "#4a6fa5",
     "紙、高科技設備、航太、汽車、機械、食品、衣物——Ontario／Quebec 為主｜Paper, high-tech equipment, aerospace, automobiles, machinery, food, clothing — mostly Ontario and Quebec"),
    ("自然資源", "Natural resources industries", 12, "#5a9460",
     "林業、漁業、農業、礦業、能源——出口大宗｜Forestry, fishing, agriculture, mining, energy — a large share of exports"),
]

TRADE_FACTS = [
    ("最大貿易夥伴｜Largest trading partner", "United States 美國｜The United States", "超過四分之三的出口銷往美國；世界最大雙邊貿易關係｜Over three-quarters of exports go to the U.S.; the world's biggest bilateral trade"),
    ("自由貿易｜Free trade", "1988 加美自由貿易 → 1994 NAFTA → 2020 CUSMA｜1988 Canada-U.S. free trade → 1994 NAFTA → 2020 CUSMA", "2021 版指南仍寫 NAFTA｜The 2021 guide still says NAFTA"),
    ("國際組織｜International groups", "G7、G20、NATO、UN、WTO、Commonwealth、La Francophonie｜G7, G20, NATO, UN, WTO, the Commonwealth, La Francophonie", "指南寫 G8；2014 俄羅斯停權後為 G7｜The guide says G8; the G7 since Russia's suspension in 2014"),
    ("邊界｜The border", "「世界最長不設防邊界」｜\"The world's longest undefended border\"", "Blaine 的 Peace Arch 象徵加美友誼｜The Peace Arch at Blaine symbolizes Canada-U.S. ties"),
    ("經濟規模｜Economy", "世界十大經濟體之一｜One of the ten largest economies in the world", "商業是經濟成長的引擎｜Commerce is the engine of economic growth"),
]

BILL_STEPS = [
    ("一讀 First Reading", "法案視為第一次宣讀並印製｜The bill is read for the first time and printed"),
    ("二讀 Second Reading", "辯論法案原則｜Members debate the bill's principle"),
    ("委員會 Committee Stage", "逐條審議｜Studied clause by clause"),
    ("報告 Report Stage", "提出修正｜Members can make amendments"),
    ("三讀 Third Reading", "辯論並表決｜Members debate and vote"),
    ("參議院 Senate", "同樣的程序｜A similar process in the Senate"),
    ("御准 Royal Assent", "總督代君主簽署 → 成為法律｜The Governor General grants royal assent → law"),
]

GOV_LEGEND = [
    ("#c8102e", "聯邦 Federal", "國防、外交、貨幣、刑法、公民身分；總理 Mark Carney｜Defence, foreign policy, currency, criminal law, citizenship; PM Mark Carney"),
    ("#4a6fa5", "省 Provincial", "教育、醫療、自然資源、公路；Ontario 省長 Doug Ford｜Education, health, natural resources, highways; Ontario Premier Doug Ford"),
    ("#5a9460", "市鎮 Municipal", "除雪、消防、大眾運輸、地方法規；Toronto 市長 Olivia Chow｜Snow removal, firefighting, transit, by-laws; Toronto Mayor Olivia Chow"),
]
